### ISSUE TITLE
Empty cells wrongly inferred as geojson

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/tableschema-py#117]
Consider the following source and code:

``` python
from jsontableschema import Table

source = [{'id': '1', 'name': 'john'},
          {'id': '2', 'name': ''},
          {'id': '3', 'name': ''},
          {'id': '4', 'name': ''},
          {'id': '5', 'name': 'ann'}]

table = Table(source)

print([f.type for f in table.schema.fields])

# Outputs `['integer', 'geojson']`

```

It's not a GeoJSON type issue per se, it just returns the last item on the [`_get_available_types()`](https://github.com/frictionlessdata/jsontableschema-py/blob/76b34498644c80b6d3fadc3e4432d0935ebbbbff/jsontableschema/infer.py#L151:L168) list. It looks like calling the [`test()`](https://github.com/frictionlessdata/jsontableschema-py/blob/76b34498644c80b6d3fadc3e4432d0935ebbbbff/jsontableschema/infer.py#L106) method on all types with an empty string will return True (so when resolving the counts there will be 2 `strings` and 3 `geojson`). I don't know the workings of the library so I don't know if returning True on `test()` is expected, but in any case it looks like we could handle empty values separately:

``` diff
diff --git a/jsontableschema/infer.py b/jsontableschema/infer.py
index b38b490..905625f 100644
--- a/jsontableschema/infer.py
+++ b/jsontableschema/infer.py
@@ -102,6 +102,8 @@ class _TypeGuesser(object):
         self.type_options = type_options or {}

     def cast(self, value):
+        if not value:
+            return ('string', 'default')
         for _type in reversed(self._types):
             result = _type(self.type_options.get(_type.name, {})).test(value)
             if result:
```

This needs more thought by someone more familiar with the library (eg do we need to distinguish between `''` and `None`, is `string` the best default, etc) but you get the idea.

Happy to submit a PR with the preferred approach with tests if you point me to the right place.

**Comment by roll** [comment]
I've run into exactly the same today (and it's also a root of our yeasterday issue with gt). 

If infer cant infer should be a string by default I suppose.

**Comment by roll** [comment]
There's related #105

**Comment by roll** [comment]
MERGED
https://github.com/frictionlessdata/jsontableschema-py/issues/105
