### ISSUE TITLE
Improve library import speed

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#118]
From my tests it will take around 1s:

```
import jsontableschema
```

**Comment by pwalsh** [comment]
why?

**Comment by roll** [comment]
I don't know) I'll profile. There are a few chunks of code which runs outside of functions and classes. But also may be it's normal because of dependencies. Juts discovered it because GT time to create a report for simple dataset could be around 100ms but overall around 2s and most of them on `jsontableschema` import.

**Comment by Fak3** [comment]
The tabulator import is instant after the fix. But the jsontableschema is still slow to import... ;( I guess it was not only affected by tabulator, but has issue itself. Can you please have a look?

**Comment by roll** [comment]
FIXED
Latest tests just show not it's around normal (around 200ms). It still needs to load profiles.
