### ISSUE TITLE
Add Support for ISO-4217 currency codes

### ISSUE THREAD

**Issue by cyberbikepunk** [frictionlessdata/tableschema-py#138]
@roll I suggest that the `NumberType.parse_currency` method could not only strip  out currency characters but also [currency codes](http://www.iso.org/iso/home/standards/currency_codes.htm). I would add a JSON file with the codes to the `data` folder and `re.sub` out just like with currency characters. Any objection?

**Comment by roll** [comment]
cc @akariv @pwalsh 

One thing about tech part of this - any files used by library should be inside `jsontableschema` folder. `data` folder is not a part of installation.

**Comment by pwalsh** [comment]
Is there compelling argument to have currency codes as JSON, and not as a tuple exported from a module (for example)?

**Comment by roll** [comment]
@pwalsh 
It's mostly minor. For a starter I'm +1 for just `CURRENCY_CODES` constant in the `number` module. 

So this feature from `jts` perspective? I'm too experienced in fiscal data.

**Comment by cyberbikepunk** [comment]
@roll @pwalsh I'll leave it to you to decide where the codes go but looking at the structure of the package, there seems to be obvious place to put it, so I would agree a `CURRENCY_CODES` constant in order.

**Comment by pwalsh** [comment]
@akariv WDYT on this?

**Comment by akariv** [comment]
Given my stance on frictionlessdata/specs#258, I think this is irrelevant.
