### ISSUE TITLE
Implement Field.uncast/stringify_value method to save tables

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#161]
# Overview

For now e.g in `tableschema.Table.save()` we just use default string representation for the cast value. But there could be `Field.uncast/stringify_value` method to stringify values following field format etc. Also could be useful for the end-users as a part for Field API.

**Comment by OriHoch** [comment]
there is a basic implementation of this here - https://github.com/hasadna/knesset-data-datapackage/blob/master/knesset_datapackage/utils.py#L42

**Comment by roll** [comment]
Implemented in [Frictionless Framework](https://github.com/frictionlessdata/frictionless-py)
