### ISSUE TITLE
Consider alternative Storage backends for large files on disk

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/tableschema-py#169]
- [ ] HDF5 http://www.h5py.org/
- [ ] Feather https://github.com/wesm/feather
- [ ] Blaze http://blaze.readthedocs.io/en/latest/index.html

See: https://github.com/frictionlessdata/pilot-dm4t/issues/22#issuecomment-307781463

**Comment by pwalsh** [comment]
also see https://github.com/frictionlessdata/datapackage-pipelines/issues/66

**Comment by roll** [comment]
@danfowler 
Could you please link also to the problem it has to solve. Like example when you've run into limitations of current solutions etc.

**Comment by roll** [comment]
MOVED
https://github.com/frictionlessdata/implementations/issues/20
