### ISSUE TITLE
Tiebreaker in _TypeResolver

### ISSUE THREAD

**Issue by strets123** [frictionlessdata/tableschema-py#176]
_TypeResolver should default to calling something a string if there is a tie between string and another type.

Currently I am experiencing inconsistent behaviour for calls like 

    import unittest
    from io import BytesIO
    
    from tabulator import Stream
    from tableschema import infer
    
    class BooleanTestCase(unittest.TestCase):
        def test_check_type(self):
    
            data = BytesIO(b"foo\tbaraz\t\n1\ttst\tm tst\n\tf\tother test")
    
            with Stream(data, format="tsv") as stream:
                sample = stream.sample
            schema = infer(sample[0], sample[1:])
            assert schema["fields"][1]["type"] == "string"

Here there is a tie between boolean and string. If the test is run on its own then 1/2 the time it fails. I think that the best way to follow "in the face of ambiguity refuse the temptation to guess" would be for the typeresolver to just stick to string. 

Or perhaps even to have a configurable threshold % of strings at which string would be the default.

**Comment by roll** [comment]
I agree we should have it deterministic.
