### ISSUE TITLE
License issue: 'rfc3987' is GPL

### ISSUE THREAD

**Issue by MuhammadAlkarouri** [frictionlessdata/tableschema-py#191]
Hi,

The Tableschema library lists as part of its requirements the library `rfc3987>=1.3,<2.0`. The library [rfc3987](https://github.com/dgerber/rfc3987) is GPL licensed. And it seems not to be used anywhere in the source code (according to a quick grep check).

The library [rfc3986](http://rfc3986.readthedocs.io/en/latest/) is used, but that is Apache licensed and is less restrictive.

Can `rfc3987` be removed from the dependencies?

**Comment by pwalsh** [comment]
@roll please sort this.

**Comment by roll** [comment]
@MuhammadAlkarouri 
Hi. Thanks for heads-up. Fixed and released as `tableschema=>1.0.1`
