### ISSUE TITLE
Validation for URI is inconsistent with tablechema-js if field value is IP

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/tableschema-py#204]
Not sure which one of this is correct - is IP URI or not - but there is a difference between how `Schema` modules work in `tableschema-py` and `tablechema-js`.  For example if you try and cast `'19.16.162.96'` with `type=string` and `format=uri` in JS it works fine:

```
const {Schema} = require('tableschema')
let schema = await Schema.load({'fields': [{'name': 'ip', 'type': 'string', 'format': 'uri'}]})
schema.castRow(['19.16.162.96'])
```

But if you try and do same in python it will fail with cast error: `can't cast value "19.16.162.96" for type "string" with format "uri"`

```
from tableschema import Schema
schema = Schema({'fields': [{'name': 'ip', 'type': 'string', 'format': 'uri'}]})
schema.cast_row(['19.16.162.96'])
```

This gives us some hard times if we use `tableschema-js` library to infer schema from row data and process the data later with python library that uses `tablschema-py` to cast values (like [datapackage-pipelines](https://github.com/frictionlessdata/datapackage-pipelines))

**Note:**  in the earlier version of `tableschema-js` they were aligned. I believe they've split after this commit https://github.com/frictionlessdata/tableschema-js/commit/fce178a113338ceb40966aae80fffe9a5633d158

**Comment by AcckiyGerman** [comment]
@zelima The `validator` JS lib, has a method `isURL()` , which is used in `tableschema-js`

`isURL()` has an option `{require_protocol: true}` which will treat all usual IP as non-valid URL.

I think this could help. Let me check, how is this realised in `tableschema-PY`, may be there is an options to Allow validation of pure IP as URL

**Comment by AcckiyGerman** [comment]
Tableschema-PY:  I could allow IP as URL by changing this:

```python
_uri_validator = rfc3986.validators.Validator().require_presence_of('scheme')
```
