### ISSUE TITLE
Infer limit does not always work

### ISSUE THREAD

**Issue by Transrian** [frictionlessdata/tableschema-py#212]
Welcome back guys, one last problem, I hope :)

Got a little problem with the infer limit describe here : https://github.com/frictionlessdata/tableschema-py#tableinferlimit100-confidence075

There are cases where the limit work, cases where it does not :
- When the limit is < to the 'default' limit (100), limit is well changed
- When the limit is > to the 'default' limit (100), it is set to 100 (or 99 depending of headers presence). Whatever you try (120, 1000, ...)

I took a fast look at the code, didn't found anything related. Here is how to reproduce the problem (come from my previous issue #209 ):

```python
from tabulate import tabulate
from tableschema import Table


table = Table("test.csv")

table.infer(103, confidence=1)

print(tabulate(table.schema.descriptor['fields'], headers="keys", tablefmt="pipe"))

try:
    table.read(keyed=False, cast=True)
except Exception as err:
    print(err.errors)
    exit(1) 
```

**test.csv**
https://gist.github.com/Transrian/971cf7bc9ab0c4558cecca2fd6b4876d#file-test-csv

Result:
```bash
python3 test2.py 
| name   | type    | format   |
|:-------|:--------|:---------|
| a      | integer | default  |
| b      | integer | default  |
[CastError('Field "b" can\'t cast value "1.1" for type "integer" with format "default"',)]
```

Problematic line (line 101) should be treated during processing, but is not. If you move it to previous line (100), it work well

Thanks for all!

**Comment by Transrian** [comment]
I think it's more related to tabulator than to tableschema, limit seems to be lost at those lines : 

https://github.com/frictionlessdata/tableschema-py/blob/d47b6d73ab3ea1051c866b93b6e2b9202bbd40b1/tableschema/table.py#L149-L151

(Before, limit seems to be good, and after limit is not the wanted one) -> perhaps a Stream error ?

May someone confirm ?

**Comment by pajachiet** [comment]
This error is linked to tabulator's stream. 

It has a default `sample_size` of 100 (cf [code](https://github.com/frictionlessdata/tabulator-py/blob/master/tabulator/stream.py#L48)).

The stream is created at `Table` construction. A way to fix the issue is to pass a `sample_size` option, that will be passed to stream constructor [here](https://github.com/frictionlessdata/tableschema-py/blob/master/tableschema/table.py#L44).

Example
```
table = Table(csv_path, sample_size=limit)
table.infer(limit=limit)
```
