### ISSUE TITLE
Save tabular data as json file

### ISSUE THREAD

**Issue by iamjenmackle** [frictionlessdata/tableschema-py#213]
Is there a way to use the 'table.save()' method but save the file as json not csv? Right now it says "json is not supported". It would be great if you could point me to the right spot to adjust the code.

**Comment by roll** [comment]
@iamjenmackle 
Unfortunately it's not supported yet. 

If you're interested in making a contribution the support of saving as JSON will be very simple to add. We just need to implement this class - https://github.com/frictionlessdata/tabulator-py/blob/master/tabulator/writers/csv.py - for json. Then `table.save()` will be able to work with this automatically after `tabulator` update.

**Comment by iamjenmackle** [comment]
Alright, I might give that a try. Thanks for your help. 

Could you give me a hint on how to go about implementing that?

**Comment by roll** [comment]
https://github.com/frictionlessdata/tabulator-py/issues/235

**Comment by roll** [comment]
It's not supported with `tabulator@1.40+`

```python
from tableschema import Table

table = Table('data/data.csv')
table.infer()
table.save('tmp/data.json')
table.save('tmp/data-keyed.json', keyed=True)
```
