### ISSUE TITLE
Using backports.csv instead unicodecsv in tabulator and tableschema

### ISSUE THREAD

**Issue by RockBomber** [frictionlessdata/tableschema-py#214]
Do you have plans to using backports.csv instead unicodecsv in tabulator and tableschema?

backports.csv is more recent than unicodecsv

**Comment by pwalsh** [comment]
@RockBomber no there are no plans. Are there any bugs, or is there any additional functionality that we don't have now, that would warrant a change?

**Comment by roll** [comment]
I'm closing as Python2 is deprecated now
