### ISSUE TITLE
CastError for ints when entered as floats

### ISSUE THREAD

**Issue by vincentchevrier** [frictionlessdata/tableschema-py#215]
In this minimal example:
```
from datapackage import Package

DESCRIPTOR = {
  'resources': [
    {
      'name': 'teams',
      'data': [
        ['id'],
        [1.0],
        [2.0]
      ],
      'schema': {
        'fields': [
          {'name': 'id', 'type': 'integer'}
        ]
      }
    }
  ]
}

# Check
package = Package(DESCRIPTOR)
teams = package.get_resource('teams')
teams.read()

```
the `teams.read()` raises a `CastError` triggered by the `1.0` float. If it is represented a `1` or as `'1'` there are no `CastError`s.
Perhaps enable automatic casting of `float` to `int` or document the behavior.

**Comment by roll** [comment]
cc @akariv WDYT? 

The specs are shy on it...

**Comment by akariv** [comment]
Yes, automatic casting makes sense in case there's a float with no fraction - especially since there are languages which don't have separate types for integers and floats (e.g. JS)

```javascript
typeof(1)  # "number"
typeof(1.0)  # "number"
1==1.0  # true
```

**Comment by roll** [comment]
@akariv 
Thanks

@vincentchevrier 
Would you like to propose a PR for https://github.com/frictionlessdata/tableschema-py/blob/master/tableschema/types/integer.py?
