### ISSUE TITLE
Changing field descriptor does not alter parent schema descriptor

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/tableschema-py#217]
After updating a field descriptor and then committing the schema that it is part of, the new schema descriptor is unchanged. E.g.

```py
print('Before Commit: {}'.format(mines_table.schema.descriptor['fields'][10]))
mines_table.schema.get_field('STATE').descriptor.update({'description': 'State abbreviation.'})
print('Result of Commit: {}'.format(mines_table.schema.commit()))
print('After Commit: {}'.format(mines_table.schema.descriptor['fields'][10]))
print('Field Descriptor: {}'.format(mines_table.schema.get_field('STATE').descriptor))
```
yields
```py
Before Commit: {'name': 'STATE', 'type': 'string', 'format': 'default'}
Result of Commit: False
After Commit: {'name': 'STATE', 'type': 'string', 'format': 'default'}
Field Descriptor: {'name': 'STATE', 'type': 'string', 'format': 'default', 'description': 'State abbreviation.'}
```

The fact that the `commit()` is returning `False` means that `__current_descriptor` and  `__next_descriptor` are comparing identical (the schema doesn't think there's anything to update).  The schema calls `self.__build()` if a field is added or removed using `schema.add_field()` or `schema.remove_field()` but there's no method for changing an existing field's descriptor via the schema object. Maybe there should be an `update_field()` as well? Because the ordering of the fields in the list of fields is important (the spec says it should be the same as the ordering of the fields in the CSV file), simply removing the field and re-adding it (which appends it to the end of the list of fields) isn't a good option.

Within the `Field` object there's no `commit()` method and no recording of changes within the descriptor (no `__current_descriptor` vs. `__next_descriptor`) so the only way to update the descriptor is to directly alter the dictionary, which means there's nowhere to put a hook for updating the parent schema. There's also no parent schema listed within the `Field` object, so it can't know what schema to update anyway.

**Comment by roll** [comment]
Should be fixed in https://github.com/frictionlessdata/tableschema-py/pull/231

Please re-open if it's not
