### ISSUE TITLE
Foreign and Primary Key Inference

### ISSUE THREAD

**Issue by datavistics** [frictionlessdata/tableschema-py#234]
Between multiple tables is it possible to infer Foreign keys and Primary keys for individual tables?

I read through the documentation, but didn't see anything on multiple tables.

Thanks!

**Comment by roll** [comment]
Hi, no it's not at the moment. I'm marking it as a feature request. Thanks!

**Comment by roll** [comment]
Closing it ATM as it's our of the scope we can target
