### ISSUE TITLE
Allow use of Python 3.7 with tableschema

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/tableschema-py#238]
For some reason, We are finding that including `tableschema` in our `conda` environment is blocking us from using python 3.7 in [PUDL](https://github.com/catalyst-cooperative/pudl) is there some reason why the package is actually incompatible with 3.7, or does some configuration/dependency requirement just need to be updated to include 3.7 as a possibility? This problem persists even with `tableschema` v1.5.1 via `conda-forge`

**Comment by zaneselvans** [comment]
Ah, it looks like maybe this is coming from a constraint within the `datapackage` python package (`cchardet[version='>=1.0,<2.0']`) on the versions of [cchardet](https://github.com/PyYoshi/cChardet), which appears to have added support for Python 3.7 about 8 months ago.

**Comment by zaneselvans** [comment]
But looking at the `setup.py` for `datapackage-py` the only cchardet requirement is `cchardet>=1.0` so... where is this constraint arising. Hmm.

**Comment by zaneselvans** [comment]
Ahh, but here the more restrictive requirement shows up:

```
(pudl) %0 ~/code/catalyst/pudl% conda search datapackage=1.6.0 --info                                                        zane@walkabout
Loading channels: done
datapackage 1.6.0 py_0
----------------------
file name   : datapackage-1.6.0-py_0.tar.bz2
name        : datapackage
version     : 1.6.0
build       : py_0
build number: 0
size        : 40 KB
license     : MIT
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/datapackage-1.6.0-py_0.tar.bz2
md5         : 301bccf1d84bac7e45aec0d500f400cc
timestamp   : 2019-04-11 14:33:33 UTC
dependencies: 
  - cchardet >=1.0,<2.0
  - click >=6.7,<7.0
  - jsonpointer >=1.10,<2.0
  - jsonschema >=2.5,<3.0
  - python
  - requests >=2.8,<3.0
  - six >=1.10,<2.0
  - tableschema >=1.1.0,<2.0
  - tabulator >=1.3,<2.0
  - unicodecsv >=0.14,<2.0
```

**Comment by zaneselvans** [comment]
I have create a similar issue in `datapackage-py` since that's where the problem is:

https://github.com/frictionlessdata/datapackage-py/issues/237

**Comment by zaneselvans** [comment]
With the release by @roll of datapackage 1.6.2, closing [this issue](https://github.com/frictionlessdata/datapackage-py/issues/237), the blocking `cchardet` requirement seems to have gone away, but now a similar issue seems to be coming up again on `tablechema-py`.  If I tell my environment to use Python 3.7, I get:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python[version='>=3.7']
  - tableschema
Use "conda search <package> --info" to see the dependencies for each package.
```

And the `tableschema` dependency info that comes up has many maximum versions:

```
Loading channels: done
tableschema 1.5.1 py_0
----------------------
file name   : tableschema-1.5.1-py_0.tar.bz2
name        : tableschema
version     : 1.5.1
build       : py_0
build number: 0
size        : 33 KB
license     : MIT
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/tableschema-1.5.1-py_0.tar.bz2
md5         : 8472ec02926656844af60fe14f0f3f72
timestamp   : 2019-06-06 13:03:12 UTC
dependencies: 
  - click >=3.3,<8.0
  - isodate >=0.5.4,<2.0
  - jsonschema >=2.5,<3.0
  - python
  - python-dateutil >=2.4,<3.0
  - requests >=2.5,<3.0
  - rfc3986 >=1.1.0,<2.0
  - six >=1.9,<2.0
  - tabulator >=1.3,<2.0
  - unicodecsv >=0.14,<2.0
```

So, not sure where they are coming from.

**Comment by roll** [comment]
I've done the same as I did for `datapackage` (rebasing on `tabulator@1.20`). So it will be fixed on the next conda forge update. Thanks!

**Comment by zaneselvans** [comment]
Hmm, I'm still getting an unresolvable dependency with Python 3.7 and the new version 1.5.2 of tableschema:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python[version='>=3.7']
  - tableschema
```
and
```sh
conda search tableschema=1.5.2 --info
```
still shows a restrictive set of versions:
```
tableschema 1.5.2 py_0
----------------------
file name   : tableschema-1.5.2-py_0.tar.bz2
name        : tableschema
version     : 1.5.2
build       : py_0
build number: 0
size        : 33 KB
license     : MIT
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/tableschema-1.5.2-py_0.tar.bz2
md5         : a83495e51aac7269cac7e4848d29d641
timestamp   : 2019-06-10 11:20:46 UTC
dependencies: 
  - click >=3.3,<8.0
  - isodate >=0.5.4,<2.0
  - jsonschema >=2.5,<3.0
  - python
  - python-dateutil >=2.4,<3.0
  - requests >=2.5,<3.0
  - rfc3986 >=1.1.0,<2.0
  - six >=1.9,<2.0
  - tabulator >=1.3,<2.0
  - unicodecsv >=0.14,<2.0
```
Looking at the current set of version requirements on `tabulator` it looks like the `cchardet` requirements are still lingering over there. So I opened an [issue in that repo](https://github.com/frictionlessdata/tabulator-py/issues/263)

**Comment by roll** [comment]
Meta issue for this problem is here - https://github.com/frictionlessdata/tabulator-py/issues/263
