### ISSUE TITLE
Format "None" 

### ISSUE THREAD

**Issue by alw4ey** [frictionlessdata/tableschema-py#245]
I have been trying to do the tableschema example (for writing to the database), but I consistently get the following error on table.save('articles', backend='sql', engine=db):

(lastchance) -bash-4.2$python create_lastchance_table.py
Traceback (most recent call last):
  File "create_lastchance_table.py", line 14, in <module>
    table.save('articles', backend='sql', engine=db)
  File "/scratch/miniconda3/envs/lastchance/lib/python3.7/site-packages/tableschema/table.py", line 174, in save
    stream.save(target, **options)
  File "/scratch/miniconda3/envs/lastchance/lib/python3.7/site-packages/tabulator/stream.py", line 417, in save
    raise exceptions.FormatError(message)
tabulator.exceptions.FormatError: Format "None" is not supported 

Writing to a file works fine (without errors), but we are really trying to use Frictionless Data as a standard for loading datafiles into databases.  

Thanks!

**Comment by roll** [comment]
@alw4ey 
Hi, is it possible (if it's public) to share some data and code you use so I will be able to try reproducing the problem? 

> but we are really trying to use Frictionless Data as a standard for loading datafiles into databases.
:+1: cc @lwinfree

**Comment by alw4ey** [comment]
Sure, see attached; but this is just a reduced copy of the example.

Also, here is my pip requirements.txt listing, in case it offers some insight into the problem:
attrs==19.1.0
bitarray==0.9.3
cchardet==2.1.4
certifi==2019.6.16
chardet==3.0.4
Click==7.0
et-xmlfile==1.0.1
idna==2.8
ijson==2.4
isodate==0.6.0
jdcal==1.4.1
jsonlines==1.2.0
jsonschema==3.0.1
linear-tsv==1.1.0
openpyxl==2.4.11
psycopg2==2.8.3
pybloom-live==3.0.0
pyrsistent==0.15.3
python-dateutil==2.8.0
requests==2.22.0
rfc3986==1.3.2
six==1.12.0
SQLAlchemy==1.3.5
tableschema==1.6.0
tableschema-sql==0.11.0
tabulator==1.23.0
unicodecsv==0.14.1
urllib3==1.25.3
xlrd==1.2.0
[create_lastchance_table.py.txt](https://github.com/frictionlessdata/tableschema-py/files/3394932/create_lastchance_table.py.txt)

**Comment by roll** [comment]
@alw4ey 
Sorry for the slow response. The example wasn't up-to-date. Could you please try:

```python
# pip install sqlalchemy tableschema-sql
import sqlalchemy as sa
from tableschema import Table

# Create SQL database
db = sa.create_engine('sqlite://')

# Data from WEB, schema from MEMORY
SOURCE = 'https://raw.githubusercontent.com/frictionlessdata/tableschema-py/master/data/data_infer.csv'
SCHEMA = {'fields': [{'name': 'id', 'type': 'integer'}, {'name': 'age', 'type': 'integer'}, {'name': 'name', 'type': 'string'}] }

# Open from WEB save to SQL database
table = Table(SOURCE, schema=SCHEMA)
table.save('articles', storage='sql', engine=db)

# Open from SQL save to DRIVE
table = Table('articles', storage='sql', engine=db)
table.infer()
table.schema.save('tmp/articles.json')
table.save('tmp/articles.csv')

# Open from DRIVE print to CONSOLE
table = Table('tmp/articles.csv', schema='tmp/articles.json')
print(table.read(keyed=True))
# Will print
# [{'id': 1, 'age': 39, 'name': 'Paul'}, {'id': 2, 'age': 23, 'name': 'Jimmy'}, {'id': 3, 'age': 36, 'name': 'Jane'}, {'id': 4, 'age': 28, 'name': 'Judy'}]
```

**Comment by roll** [comment]
Please let me know if the problem still exists

**Comment by alw4ey** [comment]
Nope, this took care of it, thanks!
