### ISSUE TITLE
Add constraint or option to check is_finite in cast_number

### ISSUE THREAD

**Issue by micimize** [frictionlessdata/tableschema-py#249]
I know `NaN` and `INF` are in spec, but [we should add an optional constraint](https://github.com/frictionlessdata/specs/issues/393#issuecomment-527938373). Many systems don't expect (or want to reject) non-finite numbers.

**Comment by roll** [comment]
Can you please elaborate on how you see it? For now, if I understand correctly any `INF/Nan` will raise a validation error.

**Comment by micimize** [comment]
@roll they don't - as per the linked issue and the [table schema spec](https://frictionlessdata.io/specs/table-schema/#number) `NaN, INF, -INF` are allowed numbers. 

I'm proposing a constraint for disallowing them, like `{ "finite": true }`.

**Comment by roll** [comment]
@micimize 
I mean currently, `tableschema-py` will raise an error if we try something like this:
```
Field({'type': 'number'}).cast_value('INF')
```
I would suggest opening an issue for the specs first to clarify it on the specs level - https://github.com/frictionlessdata/specs/issues

**Comment by micimize** [comment]
no, that exact code yields `Decimal('Infinity')`on `tableschema==1.7.4`:
```python
from tableschema import Field
Field({'type': 'number'}).cast_value('INF')
#> Decimal('Infinity')
```

But anyways, I've made a specs issue frictionlessdata/specs/issues/644

**Comment by roll** [comment]
@micimize 
Wow. I didn't know =) So, yea, then we need to process it through the specs

**Comment by roll** [comment]
Let's re-open when it's done in the specs - https://github.com/frictionlessdata/specs/issues/644
