### ISSUE TITLE
Foreign key error in a data package

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#252]
# Overview

https://travis-ci.org/frictionlessdata/datapackage-py/jobs/589890348

> UnboundLocalError: local variable 'refValues' referenced before assignment

@paulgirard could you please take a look if you have time

**Comment by paulgirard** [comment]
Ok I am on it.

**Comment by paulgirard** [comment]
I wrote a fix : https://github.com/frictionlessdata/tableschema-py/pull/253

**Comment by paulgirard** [comment]
By the way sorry for having introduced a regression. Should have ran datapackage tests.

**Comment by roll** [comment]
@paulgirard 
Thanks for your help! And no worries at all. 

If we have merged a regression like this it's a bug in our tests and CI approach (we need to rebase on Github Actions for better testing). Contributors are not responsible for situations when all the tests pass.

**Comment by roll** [comment]
https://travis-ci.org/frictionlessdata/datapackage-py/builds/589890347 :+1:
