### ISSUE TITLE
Django ORM

### ISSUE THREAD

**Issue by kootenpv** [frictionlessdata/tableschema-py#255]
Are there ideas (or even hidden examples) that show how to use this for Django (I only see a sqlalchemy example)

**Comment by roll** [comment]
Hi @kootenpv,

Could you please provide an example in which context?

**Comment by pikhovkin** [comment]
> Are there ideas (or even hidden examples) that show how to use this for Django (I only see a sqlalchemy example)

for example [like this](https://github.com/pikhovkin/django-schema-viewer/blob/main/schema_viewer/schema.py#L34)
