### ISSUE TITLE
Harden schema validation

### ISSUE THREAD

**Issue by pierredittgen** [frictionlessdata/tableschema-py#264]
# Schema validation

## Currently

Simple table schema containing one single field, defined as `number` using a  [constraint](https://frictionlessdata.io/specs/table-schema/#constraints) `maxLengh` that applies only to collections.

```python
import tableschema
descriptor = {
  "fields": [
    {
       "name": "foo",
       "type": "number",
       "constraints": {
         "maxLength": 3
       }
    }
  ]
}
schema = tableschema.Schema(descriptor, strict=True)
print(schema.valid)
# True
```

Schema is stated as valid.

## Proposal

I would appreciate that the previous example failed with an error message as "field foo: built-in maxLength constraint can't be applied to number field type"

This would help to detect problems earlier when writing a new table schema.

@roll would you accept to incorporate these types of additional checks in tableschema validation?

**Comment by roll** [comment]
Hi @pierredittgen,

I think it's a valuable check. 

We have a slightly weird code for custom schema validation (additional to JSONSchema rules) here - https://github.com/frictionlessdata/tableschema-py/blob/master/tableschema/profile.py#L83

So adding the mentioned logic there will resolve this issue

**Comment by pierredittgen** [comment]
I created a pull-request: https://github.com/frictionlessdata/tableschema-py/pull/268

**Comment by roll** [comment]
FIXED in https://github.com/frictionlessdata/tableschema-py/pull/268
