### ISSUE TITLE
Pass in missingValues

### ISSUE THREAD

**Issue by cschloer** [frictionlessdata/tableschema-py#265]
# Overview

I'm not totally sure if this should be in the tabulator or tableschema repo, you tell me @roll.

We are creating a tool for scientists to submit datasets. In that tool we want to infer the schema in order to run validation checks with goodtables and give automated feedback to the scientists. Therefore the scientists will have to pass in their own configuration values such as header row, skipped rows, etc. It is very important that they are also able to pass in missingValues to the dataset in order for the schema to be properly inferred and validated. I am requesting:

1. Have those passed in missingValues show up in the schema descriptor
2. Have those passed in missingValues be taken in account when the schema is inferred.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
@cschloer 
Do I understand correctly that you need something like:
```python
goodtables(..., infer_schema=True, missingValues=['some1', 'some2'])
```
The specs support per table level of missing values at the moment. Should it be per column for your needs?

**Comment by cschloer** [comment]
yes exactly. For this particular project per table level is fine. However, per column missingValues would definitely be useful for other areas.

**Comment by roll** [comment]
@cschloer 
I've evaluated different options and now I think that it's already available and more flexible than if we add an option to `goodtables`:

```csv
col1,col2,col3
1,2,3
1,2,3
1,2,3
1,2,3
1,2,3
1,2,3
1,2,3
1,2,3
1,2,3
-,x,y
```

```python
import goodtables
import tableschema

source = 'tmp/missing_values.csv'
schema = tableschema.infer(source, limit=10)
schema.update({ 'missingValues': ['-'] })
report = goodtables.validate(source, schema=schema, skip_checks=['duplicate-row'])
print(report)
```

The client library (a `goodtables` user) just needs to infer a schema using `tableschema.infer` (also customizable regarding confidence etc) and to change whatever schema's properties are needed in the client code. 

I'm closing. Please re-open if it will not work for the project

**Comment by cschloer** [comment]
Just a quick follow-up to determine if this will fit our needs: I see how this fixes goodtables errors, but doesn't this still have the problem of the schema being improperly inferred by tableschema?

 If a missingValue is in the initial n cells of a field, where n is the sample_size, won't it improperly infer the field to be a string? As you said you can adjust the confidence of the tableschema's infer but that seems like a rather imprecise and unreliable way to achieve the best possible inference. Or am I incorrectly assuming how the confidence parameter works?

Let me know if that question wasn't clear.

**Comment by roll** [comment]
@cschloer 
I've created a separate issue to improve the precision of the infer function - https://github.com/frictionlessdata/tableschema-py/issues/266

Current implementation should work for most cases because it's based on confidence. So I'd say that #266 should be less critical

**Comment by cschloer** [comment]
Great, with #266 it should presumably work 100% of the time, though I believe you that it it'll work most of the time without it!
