### ISSUE TITLE
Composite PK uniqueness check

### ISSUE THREAD

**Issue by duncdrum** [frictionlessdata/tableschema-py#275]
# Overview

Composite Primary Keys consistently fail uniqueness checks against first column of PK
See https://github.com/frictionlessdata/goodtables-py/issues/353 

the following test masks this issue, it looks like it expects a uniqueness error to be thrown, when there shouldn't be one. 

https://github.com/frictionlessdata/tableschema-py/blob/3b01bc44b1b0dfe3764ae270a07e4bbc539b4bb8/tests/test_table.py#L1028

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
I'm closing this issues because the tests look correct to me anyway `goodtables` doesn't use `tableschema` for uniqueness checks

Let's discuss in https://github.com/frictionlessdata/goodtables-py/issues/353
