### ISSUE TITLE
EncodingError: Cannot parse the source "XXXX.csv" using "utf-8" encoding at "1099"

### ISSUE THREAD

**Issue by xixiaodong** [frictionlessdata/tableschema-py#280]
# Overview
How can I resolve the encoding error?

Thanks.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @xixiaodong,

You can pass the encoding explicitly:

```python
table = Table('path.csv', encoding='<your-encoding>')
```

In your case, it seems it guessed the encoding wrong

**Comment by xixiaodong** [comment]
Thank you so much!
