### ISSUE TITLE
Current dependency bounds are causing warnings on install

### ISSUE THREAD

**Issue by decentral1se** [frictionlessdata/tableschema-py#283]
# Overview

Carried over from https://github.com/frictionlessdata/tableschema-pandas-py/issues/36.

Currently installing the following dependency list:

```cfg
install_requires =
  click >= 7.1.2, < 8
  datapackage >= 1.14.1, < 2
  jsontableschema-pandas >= 0.5.0, < 1
  pandas >= 1.0.4, < 2
  rich >= 2.2.3, < 3
  typer >= 0.2.1, < 1
```

The dependency bounds on the package are causing warnings which may move into errors if we leave it sit for too long. Here are the warnings I am currently seeing. One is from a sub-dependency which may need another issue. Let's see.

> ERROR: jsontableschema 0.10.1 has requirement click<7.0,>=3.3, but you'll have click 7.1.2 which is incompatible.
> ERROR: jsontableschema 0.10.1 has requirement jsonschema<3.0,>=2.5, but you'll have jsonschema 3.2.0 which is incompatible.
> ERROR: tableschema 1.19.2 has requirement rfc3986>=1.1.0, but you'll have rfc3986 0.4.1 which is incompatible.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi,

You need to use `tableschema-pandas` instead of `jsontableschema-pandas`

Please re-open if it didn't help

**Comment by decentral1se** [comment]
Works! Thanks :+1:
