### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by xixiaodong** [frictionlessdata/tableschema-py#284]
# When trying to print out the errors using the schema check, the code took up a lot of my memory

I was following the codes 
![image](https://user-images.githubusercontent.com/33994231/84797969-5159af80-aff2-11ea-8920-c21c3ddc1346.png)

It should not take up a whole lot of memory right? (since it is only an iterator)
What is the best practice here if I don't want to use a lot of memory when trying to get all the data errors that did not comply with the schema?

Many thanks,
Xiaodong
---

 @roll

**Comment by roll** [comment]
Hi @xixiaodong,

I'm re-working the error system at the moment for the next version of the lib. I hope it will be available in about a month

**Comment by roll** [comment]
[Frictionless Framework](https://github.com/frictionlessdata/tableschema-py#tableschema-py) is now released. 

Please try it, the whole error collection system has been reworked.
