### ISSUE TITLE
tableschema file not found raises an exception instead of an error message

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/tableschema-py#286]
Related to #285

`tableschema infer does_not_exist`

Raises an exception instead of showing an error message. I think that it would be nicer for users to have an error message

The same happens with `tableschema validate invalid_file`. A more succint error message and perhaps a suggestion on how to fix it would be appreciated by users not used to read Python exceptions.

Tableschema version: 1.18

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
MERGED into https://github.com/frictionlessdata/tableschema-py/issues/285
