### ISSUE TITLE
Max confidence is not working properly for large csvs

### ISSUE THREAD

**Issue by NilsJPWerner** [frictionlessdata/tableschema-py#289]
# Overview

I am trying to infer the schema of a csv with 300k rows. One column is primarily integers but 0.6% of values are strings like "1A". I want this column to be inferred as type string so I set the confidence parameter to 1.0 when using the infer function. However it still gets inferred to an integer and then fails to read the csv and throws a CastError. My understanding of the confidence parameter was that setting it to 1 would make it 100% permissive.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @NilsJPWerner,

I'm not fully sure how the `tableschema`'s algorithm works regarding inferring but https://github.com/frictionlessdata/frictionless-py should guarantee type compatibility with `infer_confidence=1` (https://colab.research.google.com/drive/1eIq1ZTUntJplRxkGHxmqlxZ0zyXCm0wU#scrollTo=YH3-nkU_1Q0j)

Another question, that both still only infer types from a data sample (https://colab.research.google.com/drive/1eIq1ZTUntJplRxkGHxmqlxZ0zyXCm0wU#scrollTo=Lx8094711HVr) and theoretically it always can have mistakes if e.g. your strings come only after NNN rows (more than sample size).

I would programmatically set this field as a string if you know it in advance

**Comment by roll** [comment]
Please re-open if needed
