### ISSUE TITLE
Ensure schemas can't be out-dated

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-py#32]
https://github.com/frictionlessdata/jsontableschema-py/blob/master/jsontableschema/schemas/json-table-schema.json

**Comment by Bjwebb** [comment]
Looks like the schema's moved to https://github.com/frictionlessdata/jsontableschema-py/blob/master/jsontableschema/schemas/json-table-schema.json now.

**Comment by danfowler** [comment]
@Bjwebb updated.  Thanks!

**Comment by pwalsh** [comment]
@danfowler what have you updated?

**Comment by danfowler** [comment]
@pwalsh the link in your comment at the top which was broken.

**Comment by roll** [comment]
@pwalsh 
why do not include?

**Comment by pwalsh** [comment]
@roll I'm worried about changes to spec not getting into the libs.

But this is quite an old issue. I'd say now the best approach is the one that @vitorbaptista took in datapackage-py:

- include schemas as git submodule
- for the pypi package, include the specific files we want
- bump the submodule + package release with schema changes
- also have an option to work over HTTP with the current file

https://github.com/frictionlessdata/datapackage-py/tree/master/datapackage/schemas

**Comment by roll** [comment]
I've checked `datapackage-py` approach - it's convenient method to update schemas (but here also we have `geojson.json` not covered by `schemas` repository). But I don't see how it resolves problem you've described - if no one runs `git pull --subtree ...` command than schema also will be out-dated. No difference between manual copy-past.

So I suppose there is no difference how we update schema directory manually or using git submodules. Difference could be add for example if we will add test checking schemas is actual.

**Comment by pwalsh** [comment]
@roll the difference is that you have a controlled way to know which version of `schemas` was in included in which release here. But either way is fine with me.
