### ISSUE TITLE
Table should support unique, primaryKey checks

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-py#33]
We can do these when we get https://github.com/okfn/tabulator-py working with streams of CSV data. We'll update the existing data methods and add new ones to to maintain lookups of previously seen data, etc, similar to what happens in parts of `goodtables` now.

**Comment by roll** [comment]
It looks like it depends on - https://github.com/frictionlessdata/jsontableschema-py/issues/34 - creating `Resource` concept because now for example `SchemaModel` has no such a thing as a separator between dataset for example (cc @georgiana-b):
```python
model = model.SchemaModel(schema)
model.cast_row(row1)
model.convert_row(row2) # check unique or may be it's other dataset?
model.convert(rows1)
model.convert(rows2) # the same question
```

**Comment by pwalsh** [comment]
@roll this can wait until after spec changes (was missing before - it is not about updating for changes to v1)
