### ISSUE TITLE
Rebase compat on six

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#83]
# Overview

`six` is a standard py2-py3 compat library and used in all other FD python packages. There is almost no difference what to use (the main use case to check something is a string) but custom `compat` need to be maintained, testes etc while `six` developers have done it for us.

**Comment by pwalsh** [comment]
I know I'm the only one here who is still not convinced this is better. 

six, in my eyes, is designed for large py2 code bases that added py3 support at some point in their lifetime. 

In any event, perhaps python-future is closer to the compat goals, and as far as I see possibly aligns better with python's own guide for porting (using __future__ imports liberally to ensure more consistent behavior across runtimes, for example).

http://python-future.org/faq.html#relationship-between-python-future-and-other-compatibility-tools

I'll be happy with six though: just sayin'.

**Comment by roll** [comment]
MERGED
#80
